"""Initial migration

Revision ID: 550eb46b04ab
Revises: 
Create Date: 2025-02-12 23:13:26.453454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '550eb46b04ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('doctor_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='appointments_pkey')
    )
    # ### end Alembic commands ###
