name: Deploy Flask App

on:
  push:
    branches:
      - main  # Runs this workflow whenever code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set Flask Environment
      run: |
        export FLASK_APP=app.py
        export FLASK_ENV=production
      
    - name: Deploy Flask App (Local Server)
      env:
        FLASK_APP: app.py
        FLASK_ENV: production
        DATABASE_URL: postgresql://postgres:Croclurksintheswamp333@localhost:5432/anthizo_healthcare
      run: |
        flask db init || true  # Initialize migrations (ignores error if already done)
        flask db migrate -m "Initial migration" || true  # Create migration (ignores if exists)
        flask db upgrade  # Apply database migrations
        nohup flask run --host=0.0.0.0 --port=5000 &
      
