name: Deploy Flask App

on:
  push:
    branches:
      - main  # Runs this workflow when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: anthizo_healthcare
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Flask Environment
      run: |
        echo "FLASK_APP=app.py" >> $GITHUB_ENV
        echo "FLASK_ENV=production" >> $GITHUB_ENV
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/anthizo_healthcare" >> $GITHUB_ENV

    - name: Deploy Flask App (Local Server)
      env:
        FLASK_APP: app.py
        FLASK_ENV: production
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/anthizo_healthcare
      run: |
        sleep 10  # Wait for PostgreSQL to start
        flask db upgrade  # Run database migrations
        nohup flask run --host=0.0.0.0 --port=5000 &
    